
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = b'|\xec\xf6t\\\xd5\x11\xf8\xccq\x12\x10\xea\xd9\x10\xb3'
    
_lr_action_items = {'INT':([0,30,],[12,12,]),'FLOAT':([0,30,],[13,13,]),'DOUBLE':([0,30,],[14,14,]),'BOOL':([0,30,],[15,15,]),'CHAR':([0,30,],[16,16,]),'INTEGER':([0,30,35,],[17,17,17,]),'Double':([0,30,35,],[18,18,18,]),'STRING':([0,30,35,],[19,19,19,]),'BOOLEAN':([0,30,35,],[20,20,20,]),'Float':([0,30,35,],[21,21,21,]),'ARRAYLIST':([0,30,],[23,23,]),'LIST':([0,30,],[24,24,]),'HASHMAP':([0,30,],[25,25,]),'DICTIONARY':([0,30,],[26,26,]),'STRUCT':([0,30,35,],[28,28,28,]),'CLASS':([0,30,35,],[29,29,29,]),'$end':([1,30,38,],[0,-1,-2,]),'EndOfStatement':([2,4,5,6,7,31,33,40,48,49,50,],[30,-4,-5,-6,-7,-3,-8,-33,-26,-27,-30,]),'Name':([3,8,9,11,12,13,14,15,16,17,18,19,20,21,22,25,26,27,28,29,32,33,34,37,41,46,],[33,-9,-10,33,-11,-12,-13,-14,-15,-16,-17,-18,-19,-20,-21,-31,-32,33,-23,-24,33,-8,-34,-22,-35,33,]),'PointerChar':([3,8,9,12,13,14,15,16,17,18,19,20,21,22,33,34,37,],[34,-9,-10,-11,-12,-13,-14,-15,-16,-17,-18,-19,-20,-21,-8,34,-22,]),'LANGLE':([10,23,24,],[35,-28,-29,]),'RANGLE':([17,18,19,20,21,22,33,37,42,],[-16,-17,-18,-19,-20,-21,-8,-22,46,]),'LSQUARE':([31,33,],[39,-8,]),'LPairBracket':([33,36,],[-8,43,]),'Number':([39,43,],[45,45,]),'RSQUARE':([44,45,],[48,-25,]),'RPairBracket':([45,47,],[-25,50,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'ExpressionStatement':([0,30,],[1,38,]),'statement':([0,30,],[2,2,]),'DataType':([0,30,],[3,3,]),'Array':([0,30,],[4,4,]),'ArrayList':([0,30,],[5,5,]),'DataStructure':([0,30,],[6,6,]),'Pointer':([0,30,],[7,7,]),'Primitive':([0,30,],[8,8,]),'NonPrimitive':([0,30,35,],[9,9,42,]),'ArrayListType':([0,30,],[10,10,]),'DataStructureType':([0,30,],[11,11,]),'Oop':([0,30,35,],[22,22,22,]),'OopType':([0,30,35,],[27,27,27,]),'NameVar':([3,11,27,32,46,],[31,36,37,40,49,]),'PointerChars':([3,34,],[32,41,]),'const':([39,43,],[44,47,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> ExpressionStatement","S'",1,None,None,None),
  ('ExpressionStatement -> statement EndOfStatement','ExpressionStatement',2,'p_ExpressionStatement','D:/Code/python/project/conceptProject/MyYacc.py',7),
  ('ExpressionStatement -> statement EndOfStatement ExpressionStatement','ExpressionStatement',3,'p_ExpressionStatement','D:/Code/python/project/conceptProject/MyYacc.py',8),
  ('statement -> DataType NameVar','statement',2,'p_statment','D:/Code/python/project/conceptProject/MyYacc.py',18),
  ('statement -> Array','statement',1,'p_statment','D:/Code/python/project/conceptProject/MyYacc.py',19),
  ('statement -> ArrayList','statement',1,'p_statment','D:/Code/python/project/conceptProject/MyYacc.py',20),
  ('statement -> DataStructure','statement',1,'p_statment','D:/Code/python/project/conceptProject/MyYacc.py',21),
  ('statement -> Pointer','statement',1,'p_statment','D:/Code/python/project/conceptProject/MyYacc.py',22),
  ('NameVar -> Name','NameVar',1,'p_NameVar','D:/Code/python/project/conceptProject/MyYacc.py',30),
  ('DataType -> Primitive','DataType',1,'p_DataType','D:/Code/python/project/conceptProject/MyYacc.py',35),
  ('DataType -> NonPrimitive','DataType',1,'p_DataType','D:/Code/python/project/conceptProject/MyYacc.py',36),
  ('Primitive -> INT','Primitive',1,'p_Primitive','D:/Code/python/project/conceptProject/MyYacc.py',42),
  ('Primitive -> FLOAT','Primitive',1,'p_Primitive','D:/Code/python/project/conceptProject/MyYacc.py',43),
  ('Primitive -> DOUBLE','Primitive',1,'p_Primitive','D:/Code/python/project/conceptProject/MyYacc.py',44),
  ('Primitive -> BOOL','Primitive',1,'p_Primitive','D:/Code/python/project/conceptProject/MyYacc.py',45),
  ('Primitive -> CHAR','Primitive',1,'p_Primitive','D:/Code/python/project/conceptProject/MyYacc.py',46),
  ('NonPrimitive -> INTEGER','NonPrimitive',1,'p_NonPrimitive','D:/Code/python/project/conceptProject/MyYacc.py',52),
  ('NonPrimitive -> Double','NonPrimitive',1,'p_NonPrimitive','D:/Code/python/project/conceptProject/MyYacc.py',53),
  ('NonPrimitive -> STRING','NonPrimitive',1,'p_NonPrimitive','D:/Code/python/project/conceptProject/MyYacc.py',54),
  ('NonPrimitive -> BOOLEAN','NonPrimitive',1,'p_NonPrimitive','D:/Code/python/project/conceptProject/MyYacc.py',55),
  ('NonPrimitive -> Float','NonPrimitive',1,'p_NonPrimitive','D:/Code/python/project/conceptProject/MyYacc.py',56),
  ('NonPrimitive -> Oop','NonPrimitive',1,'p_NonPrimitive','D:/Code/python/project/conceptProject/MyYacc.py',57),
  ('Oop -> OopType NameVar','Oop',2,'p_Oop','D:/Code/python/project/conceptProject/MyYacc.py',62),
  ('OopType -> STRUCT','OopType',1,'p_OopType','D:/Code/python/project/conceptProject/MyYacc.py',67),
  ('OopType -> CLASS','OopType',1,'p_OopType','D:/Code/python/project/conceptProject/MyYacc.py',68),
  ('const -> Number','const',1,'p_const','D:/Code/python/project/conceptProject/MyYacc.py',73),
  ('Array -> DataType NameVar LSQUARE const RSQUARE','Array',5,'p_Array','D:/Code/python/project/conceptProject/MyYacc.py',78),
  ('ArrayList -> ArrayListType LANGLE NonPrimitive RANGLE NameVar','ArrayList',5,'p_ArrayList','D:/Code/python/project/conceptProject/MyYacc.py',85),
  ('ArrayListType -> ARRAYLIST','ArrayListType',1,'p_ArrayListType','D:/Code/python/project/conceptProject/MyYacc.py',91),
  ('ArrayListType -> LIST','ArrayListType',1,'p_ArrayListType','D:/Code/python/project/conceptProject/MyYacc.py',92),
  ('DataStructure -> DataStructureType NameVar LPairBracket const RPairBracket','DataStructure',5,'p_DataStructure','D:/Code/python/project/conceptProject/MyYacc.py',100),
  ('DataStructureType -> HASHMAP','DataStructureType',1,'p_DataStructureType','D:/Code/python/project/conceptProject/MyYacc.py',106),
  ('DataStructureType -> DICTIONARY','DataStructureType',1,'p_DataStructureType','D:/Code/python/project/conceptProject/MyYacc.py',107),
  ('Pointer -> DataType PointerChars NameVar','Pointer',3,'p_Pointer','D:/Code/python/project/conceptProject/MyYacc.py',113),
  ('PointerChars -> PointerChar','PointerChars',1,'p_PointerChars','D:/Code/python/project/conceptProject/MyYacc.py',119),
  ('PointerChars -> PointerChar PointerChars','PointerChars',2,'p_PointerChars','D:/Code/python/project/conceptProject/MyYacc.py',120),
]
